---

- hosts: [mywebservers]
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
      name: "{{mywebpackageforubuntunode}}"
      state: present
    when: ansible_os_family== "Debian"

  - name: i want to start mywebserver on ubuntu
    service: 
      name: "{{mywebpackageforubuntunode}}"
      state: started
    when: ansible_os_family== "Debian"
  
  - name: i want to install webserver on redhat
    yum:
      name: "{{mywebpackageforRedHatnode}}"
      state: present
    when: ansible_os_family== "RedHat"

  - name: i want to install webserver on redhat
    service:
       name: "{{mywebpackageforRedHatnode}}"
       state: started
    when: ansible_os_family== "RedHat"

      
